---
- hosts: test-server
  sudo: yes
  tasks:
    - name: be sure nginx is installed
      yum: name=nginx state=installed
 
    - name: be sure a listen port of nginx is 8001
      command: sed -i "s/listen.*;$/listen 8001 default_server;/g" /etc/nginx/conf.d/default.conf

    - name: be sure nginx is running and enabled
      service: name=nginx state=running enabled=yes

    - name: restart nginx
      command: service nginx restart

